name: Groupfundus
favicon: null
layout_spectrum: 0.3620226753409952
typography_spectrum: 0.32307837065309286
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.12997089605778456
  lightness: 0.2515720610972494
  saturation: 0.8727060842793435
  rhythmicContrast: 0.7766895466484129
purpose: []
